# config.py
INGRESO_INICIAL = 0
DEPOSITO_MENSUAL = 1000
TASA_ANUAL = 0.0375
TASA_IMPUESTOS = 0.19
SALDO_OBJETIVO = 1000000  # 1 millón de euros
BENEFICIO_NETO_OBJETIVO = 0
COSTO_MANTENIMIENTO = 0
NOMBRE_ARCHIVO = 'Valores_Mensuales_Iniciales.xlsx'
